[package]
name = "comlogic-interpreter"
version = "0.1.0"
authors = ["alexanderacker"]
edition = "2018"
license = "GPL-2.0"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
